export class GameRoom {
  constructor(state){this.state=state;this.sockets=new Set();this.data=null;this.disconnectTimers=new Map();this.timers=new Set()}
  async load(){if(!this.data)this.data=await this.state.storage.get('room');return this.data}
  async save(){if(this.data)await this.state.storage.put('room',this.data)}
  broadcast(){if(!this.data)return;for(const w of this.sockets)if(w.readyState===1)this.sendState(w)}
  publicState(){const d=structuredClone(this.data); // redact hidden penalty details for players without permission
    if(d.penalties?.cards)d.penalties.cards=d.penalties.cards.map(c=>this.canSeePenalty(c,null)?c:{id:c.id,name:'隐藏惩罚牌',owner:c.owner||'',hidden:true,colorOwner:c.colorOwner||''});
    return d;
  }
  canSeePenalty(card,pid){if(!card.hidden)return true; if(!pid)return false; if(pid===this.data.hostId)return true; const p=this.data.players.find(x=>x.id===pid); if(!p)return false; if(this.data.penalties?.mode==='shared')return !!p.penaltyEdit; if(this.data.penalties?.mode==='personal')return card.editorIds?.includes(pid)||card.owner===pid; return false}
  sendState(ws){if(ws.readyState===1){const d=structuredClone(this.data);const pid=ws.playerId;if(d.penalties?.cards)d.penalties.cards=d.penalties.cards.map(c=>this.canSeePenalty(c,pid)?c:{id:c.id,name:'隐藏惩罚牌',owner:c.owner||'',hidden:true,colorOwner:c.colorOwner||''});ws.send(JSON.stringify({type:'state',state:d}))}}
  async fetch(req){const u=new URL(req.url);if(u.pathname.endsWith('/ws')&&req.headers.get('Upgrade')==='websocket'){const pair=new WebSocketPair(),[client,server]=Object.values(pair);server.accept();this.sockets.add(server);server.addEventListener('message',e=>this.handle(server,JSON.parse(e.data)));server.addEventListener('close',()=>this.onClose(server));server.addEventListener('error',()=>this.onClose(server));return new Response(null,{status:101,webSocket:client})}return new Response('GameRoom')}
  onClose(ws){this.sockets.delete(ws);const pid=ws.playerId;if(!pid||!this.data)return;clearTimeout(this.disconnectTimers.get(pid));const t=setTimeout(async()=>{this.disconnectTimers.delete(pid);if(![...this.sockets].some(s=>s.playerId===pid)){this.removePlayer(pid);await this.save();this.broadcast()}},30000);this.disconnectTimers.set(pid,t)}
  async handle(ws,m){try{ws.playerId=m.playerId;
    if(m.type==='create'){if(await this.load())throw Error('房间已存在');this.data={code:m.code,hostId:m.playerId,phase:'lobby',turnId:null,turnLocked:false,players:[],settings:{rule:'normal',joker:'off',jokerCount:1,direction:'cw',failTime:2,cards:[]},cards:[],penalties:{enabled:false,mode:'host',cards:[]},events:[]};this.data.settings={...this.data.settings,...m.settings};this.normalizeSettings();this.rebuild();this.addPlayer(m,true)}
    if(!this.data)this.data=await this.load();if(!this.data)throw Error('房间不存在，请确认邀请链接或房间号');
    let me=this.data.players.find(p=>p.id===m.playerId);
    if(m.type==='join'){clearTimeout(this.disconnectTimers.get(m.playerId));this.disconnectTimers.delete(m.playerId);if(!me){if(this.data.phase!=='lobby')throw Error('游戏已经开始，暂时不能加入');if(this.data.players.length>=6)throw Error('房间已满（最多6人）');this.addPlayer(m,false)}}
    me=this.data.players.find(p=>p.id===m.playerId);
    if(m.type==='leave'){if(!me)throw Error('你不在房间内');this.removePlayer(m.playerId);clearTimeout(this.disconnectTimers.get(m.playerId));this.disconnectTimers.delete(m.playerId);if(this.data.hostId===m.playerId&&this.data.players.length)this.data.hostId=this.data.players[0].id}
    if(m.type==='name'){if(!me)throw Error('请先加入房间');me.name=(m.name||'玩家').slice(0,20)}
    if(m.type==='color'){if(!me)throw Error('请先加入房间');if(m.color<0||m.color>15)throw Error('无效颜色');if(this.data.players.some(p=>p.id!==me.id&&p.color===m.color))throw Error('该颜色已被其他玩家使用');me.color=m.color}
    if(m.type==='ready'){if(me)me.ready=!me.ready}
    if(m.type==='settings'){this.updateSettings(me,m.settings)}
    if(m.type==='permissions'){if(me?.id!==this.data.hostId||this.data.phase!=='lobby')throw Error('只有房主可设置权限');this.data.permissions={...this.data.permissions,...m.permissions};for(const p of this.data.players){const q=m.permissions.players?.[p.id];if(q){p.cardView=!!q.cardView;p.cardEdit=!!q.cardEdit;p.penaltyEdit=!!q.penaltyEdit}}}
    if(m.type==='penalties'){this.updatePenalties(me,m)}
    if(m.type==='start'){if(me?.id!==this.data.hostId)throw Error('只有房主可以开始');if(this.data.players.some(p=>!p.ready))throw Error('还有玩家没有准备');if(this.data.cards.length<2)throw Error('至少需要2张公共牌');this.data.phase='playing';this.data.turnLocked=false;this.data.players.forEach(p=>{p.score=0;p.acquired=[];p.debuffs=[]});this.data.cards.forEach(c=>{c.revealed=false;c.matched=false});this.data.penalties.cards.forEach(c=>{c.revealed=false;c.matched=false});this.shuffle(this.data.cards);this.shuffle(this.data.penalties.cards);this.data.turnId=this.data.players[0].id}
    if(m.type==='end'){if(me?.id!==this.data.hostId)throw Error('只有房主可以结束');this.toLobby()}
    if(m.type==='flip')await this.flip(m.index,me?.id,m.area||'main');
    await this.save();this.broadcast();
  }catch(e){try{ws.send(JSON.stringify({type:'error',message:e.message||String(e)}))}catch{}}}
  normalizeSettings(){const s=this.data.settings;s.failTime=Math.min(10,Math.max(1,+s.failTime||2));s.jokerCount=Math.min(4,Math.max(1,+s.jokerCount||1));s.cards=Array.isArray(s.cards)?s.cards:[];this.data.permissions=this.data.permissions||{players:{}};this.data.penalties=this.data.penalties||{enabled:false,mode:'host',cards:[]}}
  addPlayer(m,host){const p={id:m.playerId,name:(m.name||'玩家').slice(0,20),color:this.freeColor(m.color),ready:false,score:0,acquired:[],debuffs:[],cardView:true,cardEdit:false,penaltyEdit:false};this.data.players.push(p);if(host)this.data.hostId=p.id;if(!this.data.permissions)this.data.permissions={players:{}}}
  removePlayer(pid){const i=this.data.players.findIndex(p=>p.id===pid);if(i<0)return;this.data.players.splice(i,1);if(this.data.hostId===pid&&this.data.players.length)this.data.hostId=this.data.players[0].id}
  freeColor(w){const used=new Set(this.data.players.map(p=>p.color));if(Number.isInteger(w)&&w>=0&&w<16&&!used.has(w))return w;for(let i=0;i<16;i++)if(!used.has(i))return i;return 0}
  canEditMain(p){return p?.id===this.data.hostId||p?.cardEdit}
  updateSettings(me,s){if(this.data.phase!=='lobby')throw Error('游戏开始后不能修改设置');if(me?.id!==this.data.hostId&&!this.canEditMain(me))throw Error('你没有修改公共区卡牌的权限');this.data.settings={...this.data.settings,...s};this.normalizeSettings();this.rebuild()}
  updatePenalties(me,m){if(this.data.phase!=='lobby')throw Error('游戏开始后不能修改惩罚牌');if(!this.data.penalties.enabled){if(me?.id!==this.data.hostId)throw Error('只有房主可开启惩罚牌');}if(m.penalties?.enabled!==undefined&&me?.id!==this.data.hostId)throw Error('只有房主可开启或关闭惩罚牌');const mode=m.penalties?.mode||this.data.penalties.mode;if(me?.id!==this.data.hostId){if(mode==='shared'&&!me?.penaltyEdit)throw Error('你没有惩罚牌编辑权限');if(mode==='personal'&&!m.card?.owner?.includes(me.id))throw Error('只能修改自己的惩罚牌')}this.data.penalties={...this.data.penalties,...m.penalties};if(m.cards)this.data.penalties.cards=m.cards; if(m.card){const i=this.data.penalties.cards.findIndex(c=>c.id===m.card.id);if(i<0)this.data.penalties.cards.push(m.card);else this.data.penalties.cards[i]={...this.data.penalties.cards[i],...m.card}}
    this.data.penalties.cards=this.data.penalties.cards.map(c=>({...c,editorIds:c.editorIds||[]}))
  }
  rebuild(){const s=this.data.settings;this.data.cards=(s.cards||[]).flatMap((c,g)=>Array.from({length:Math.max(1,+c.count||1)},()=>({id:crypto.randomUUID(),group:g,name:c.name||'未命名',owner:c.owner||'',revealed:false,matched:false})));if(s.joker==='on')for(let i=0;i<Math.min(4,Math.max(1,+s.jokerCount||1));i++)this.data.cards.push({id:crypto.randomUUID(),group:`joker-${i}`,name:'鬼牌',owner:'',joker:true,revealed:false,matched:false})}
  shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
  toLobby(){this.data.phase='lobby';this.data.turnId=null;this.data.turnLocked=false;this.data.players.forEach(p=>{p.ready=false;p.score=0;p.acquired=[];p.debuffs=[]});this.rebuild();if(this.data.penalties?.cards)this.data.penalties.cards.forEach(c=>{c.revealed=false;c.matched=false})}
  addEvent(text,type='info'){this.data.events=[...(this.data.events||[]).slice(-5),{id:crypto.randomUUID(),text,type,at:Date.now()}]}
  async flip(i,pid,area){if(this.data.phase!=='playing'||this.data.turnId!==pid)throw Error('还没轮到你');if(this.data.turnLocked)throw Error('请等待当前牌处理完成');const arr=area==='penalty'?this.data.penalties.cards:this.data.cards;const c=arr[i];if(!c||c.matched||c.revealed)throw Error('这张牌不能翻开');c.revealed=true;
    if(c.joker){this.data.turnLocked=true;this.addEvent(`👻 ${this.data.players.find(p=>p.id===pid)?.name||'玩家'} 触发了鬼牌！`,'joker');await new Promise(r=>setTimeout(r,900));this.jokerMove();arr.forEach(x=>{if(!x.matched)x.revealed=false});this.data.turnLocked=false;this.nextTurn(pid);this.checkEnd();return}
    const open=arr.filter(x=>x.revealed&&!x.matched);if(open.length<2)return;const [a,b]=open.slice(-2);this.data.turnLocked=true;
    if(a.group===b.group){a.matched=b.matched=true;this.acquire(pid,a);this.acquire(pid,b);if(area==='penalty')this.applyPenalty(pid,a);else this.scorePair(pid,a);this.data.turnLocked=false;this.checkEnd();return}
    const wait=Math.min(10000,Math.max(1000,(+this.data.settings.failTime||2)*1000));setTimeout(async()=>{if(this.data?.phase!=='playing')return;a.revealed=b.revealed=false;this.data.turnLocked=false;this.nextTurn(pid);await this.save();this.broadcast()},wait)
  }
  acquire(pid,a){const p=this.data.players.find(x=>x.id===pid);if(!p)return;p.acquired.push(a.id)}
  scorePair(pid,a){const p=this.data.players.find(x=>x.id===pid);if(!p)return;if(this.data.settings.rule==='normal')p.score+=1;else if(a.owner)p.score+=a.owner===pid?-2:1;if(a.owner&&a.owner!==pid)this.addEvent(`🎴 ${p.name} 夺走了 ${this.data.players.find(x=>x.id===a.owner)?.name||'玩家'} 的「${a.name}」`,'steal')}
  applyPenalty(pid,c){const p=this.data.players.find(x=>x.id===pid);if(!p)return;const label=c.name||'惩罚';p.debuffs.push({id:c.id,name:label,owner:c.owner||''});this.addEvent(`⚠️ ${p.name} 触发了「${label}」`,'penalty')}
  nextTurn(pid){const n=this.data.players.findIndex(x=>x.id===pid);if(n>=0&&this.data.players.length)this.data.turnId=this.data.players[(n+1)%this.data.players.length].id}
  jokerMove(){const ps=this.data.players;if(ps.length<2)return;const dir=this.data.settings.direction;const ids=ps.map(p=>p.id);const packs=ps.map(p=>p.acquired||[]);const debuffs=ps.map(p=>p.debuffs||[]);const scores=ps.map(p=>p.score);let map=[];if(dir==='random'){map=ids.map(()=>Math.floor(Math.random()*ps.length));let used=new Set();for(let i=0;i<ps.length;i++){let j=Math.floor(Math.random()*ps.length);while(used.has(j)&&used.size<ps.length)j=Math.floor(Math.random()*ps.length);used.add(j);map[i]=j}}else{const d=dir==='cw'?1:-1;map=ps.map((_,k)=>(k-d+ps.length)%ps.length)}ps.forEach((p,k)=>{p.acquired=[...packs[map[k]]];p.debuffs=[...debuffs[map[k]]];p.score=scores[map[k]]});if(this.data.settings.rule==='special')this.recalcSpecialScores()}
  recalcSpecialScores(){for(const p of this.data.players)p.score=0;for(const p of this.data.players)for(const id of p.acquired||[]){const c=this.data.cards.find(x=>x.id===id);if(c?.owner)this.data.players.find(x=>x.id===p.id).score+=c.owner===p.id?-2:1}}
  checkEnd(){if(this.data.settings.rule==='special'&&this.data.players.length===2){for(const p of this.data.players){const roleIds=this.data.cards.filter(c=>c.owner===p.id&&!c.joker).map(c=>c.group);const remaining=roleIds.some(g=>this.data.cards.some(c=>c.group===g&&!c.matched));if(roleIds.length&& !remaining){this.data.phase='finished';this.data.turnId=null;return}}}if(this.data.cards.filter(x=>!x.matched).length<=1 && (!this.data.penalties.enabled||this.data.penalties.cards.filter(x=>!x.matched).length<=1)){this.data.phase='finished';this.data.turnId=null}}
}
export default {async fetch(req,env){const u=new URL(req.url),parts=u.pathname.split('/'),code=parts[2];if(u.pathname.startsWith('/room/')&&code){const room=env.ROOM.get(env.ROOM.idFromName(code.toUpperCase()));if(parts[3]==='ws')return room.fetch(req);return env.ASSETS.fetch(new Request(new URL('/',req.url),req))}return env.ASSETS.fetch(req)}}
